# Generated by Django 2.2.7 on 2019-11-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('cover', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsfeed.NewsPublisher')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='newsfeed.NewsFeed')),
            ],
            options={
                'unique_together': {('feed', 'keyword')},
            },
        ),
    ]
